var DIRECTION;
(function (DIRECTION) {
    DIRECTION[DIRECTION["EAST"] = 0] = "EAST";
    DIRECTION[DIRECTION["WEST"] = 4] = "WEST";
    DIRECTION[DIRECTION["NORTH"] = 5] = "NORTH";
    DIRECTION[DIRECTION["SOUTH"] = 6] = "SOUTH";
})(DIRECTION || (DIRECTION = {}));
console.log(DIRECTION);
